SELECT COUNT(*) FROM CUSTOMER_HIST;

SELECT COUNT(*) FROM CUSTOMER;

SELECT COUNT(*) FROM INVENTORY;

SELECT COUNT(*) FROM PRODUCTS;

SELECT COUNT(*) FROM ORDERLINES;

SELECT COUNT(*) FROM ORDERS;


SELECT MIN(orderdate) FROM ORDERS;

SELECT MAX(orderdate) FROM ORDERS;


