SELECT COUNT(*) FROM CUSTOMER_HIST;

SELECT COUNT(*) FROM CUSTOMER;

SELECT COUNT(*) FROM INVENTORY;

SELECT COUNT(*) FROM PRODUCTS;

SELECT COUNT(*) FROM ORDERLINES;

SELECT COUNT(*) FROM ORDERS;

SELECT DISTINCT special FROM Products;
SELECT COUNT(DISTINCT common_prod_id) FROM PRODUCTS;

SELECT c FROM CUSTOMER c WHERE  NOT IN (SELECT customerid FROM CUSTOMER);



SELECT c FROM customer WHERE c BETWEEN 1 AND 10;


Commit;